# Generated by Django 4.0.5 on 2022-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='profile/default.png', null=True, upload_to='profile/'),
        ),
    ]
